name: tptp-parser

dependencies:
- base >= 4.7 && < 5
- either
- tasty-hunit
- tasty
- parsec
- transformers
- unix
- bytestring
- tar
- http-conduit
- zlib

ghc-options: -Wincomplete-patterns -Werror -fbreak-on-error

library:
  source-dirs: src
  exposed-modules:
    - TestBin
    - ParserBin

tests:
  test:
    main: test.hs
    source-dirs: bin
    dependencies: tptp-parser

executables:
  parser:
    main: parser.hs
    source-dirs: bin
    dependencies: tptp-parser 
