name: tptp-parser

extra-source-files:
- proto/**/*.proto

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

dependencies:
- base >= 4.7 && < 5
- either
- tasty-hunit
- tasty
- parsec
- transformers
- unix
- bytestring
- utf8-string
- tar
- http-conduit
- zlib
- lens
- proto-lens-runtime
- proto-lens
- microlens
- text
- containers
- mtl
- set-monad >= 0.3
- MissingH
- threads
- concurrent-extra
- unbounded-delays
- deepseq
- split
- data-ordlist
- clock
- hashable
- hashtables
- options
- array

ld-options: -static
ghc-options: -O2 -Werror -fbreak-on-error -fPIC

library:
  source-dirs: src
  exposed-modules:
    - TestBin
    - ConvBin
    - ParserBin
    - ThreadBin
    - CheckerBin
    - Proto.Tptp
    - Proto.Proof
    - Proto.Solutions

tests:
  test:
    main: test.hs
    source-dirs: bin
    dependencies: tptp-parser

executables:
  parser:
    main: parser.hs
    source-dirs: bin
    dependencies: tptp-parser 
  conv:
    main: conv.hs
    source-dirs: bin
    dependencies: tptp-parser
  thread:
    ghc-options: -threaded -with-rtsopts=-N4
    main: thread.hs
    source-dirs: bin
    dependencies: tptp-parser
  checker:
    main: checker.hs
    source-dirs: bin
    dependencies: tptp-parser
