name: tptp-parser

extra-source-files:
- proto/**/*.proto

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

dependencies:
- base >= 4.7 && < 5
- either
- tasty-hunit
- tasty
- parsec
- transformers
- unix
- bytestring
- utf8-string
- tar
- http-conduit
- zlib
- lens
- proto-lens-runtime
- proto-lens
- microlens
- lens-labels
- text
- containers
- mtl
- set-monad >= 0.3
- MissingH

ghc-options: -Wincomplete-patterns -Werror -fbreak-on-error

library:
  source-dirs: src
  exposed-modules:
    - TestBin
    - ConvBin
    - ParserBin
    - Proto.Tptp

tests:
  test:
    main: test.hs
    source-dirs: bin
    dependencies: tptp-parser

executables:
  parser:
    main: parser.hs
    source-dirs: bin
    dependencies: tptp-parser 
  conv:
    main: conv.hs
    source-dirs: bin
    dependencies: tptp-parser 
